/**
 * Express Middleware for Pino Logging
 *
 * Provides:
 * - Automatic request/response logging
 * - Request ID propagation
 * - Context-aware child loggers
 * - Performance tracking
 */

import pinoHttp from 'pino-http';
import type { Request, Response } from 'express';
import type { Logger } from 'pino';
import { requestContextMiddleware } from './context.js';
import { sanitizeRequest, sanitizeResponse } from './sanitizer.js';

/**
 * Extract user ID from request (if authenticated)
 */
function getUserId(req: Request): string | undefined {
  // Check if user is attached by auth middleware
  if ((req as any).user?.id) {
    return String((req as any).user.id);
  }
  // Check JWT token
  if ((req as any).userId) {
    return String((req as any).userId);
  }
  return undefined;
}

/**
 * Extract session ID from request
 */
function getSessionId(req: Request): string | undefined {
  // Check session middleware
  if ((req as any).session?.id) {
    return String((req as any).session.id);
  }
  // Check cookie
  if (req.cookies?.sessionId) {
    return String(req.cookies.sessionId);
  }
  return undefined;
}

/**
 * Extract tenant ID from request (for multi-tenancy)
 */
function getTenant(req: Request): string | undefined {
  // Check tenant header
  if (req.headers['x-tenant-id']) {
    return String(req.headers['x-tenant-id']);
  }
  // Check authenticated user
  if ((req as any).user?.tenant) {
    return String((req as any).user.tenant);
  }
  return undefined;
}

/**
 * Create pino-http middleware for automatic request/response logging
 */
export function createPinoHttpMiddleware(logger: Logger) {
  return pinoHttp({
    logger,

    // Generate request ID (or use existing from header)
    genReqId: (req, res) => {
      const existingId = req.headers['x-request-id'];
      if (existingId && typeof existingId === 'string') {
        return existingId;
      }
      // Will be generated by requestContextMiddleware
      return undefined;
    },

    // Customize request serialization
    serializers: {
      req: sanitizeRequest,
      res: sanitizeResponse,
    },

    // Custom log level based on status code
    customLogLevel: (req, res, err) => {
      if (res.statusCode >= 500 || err) {
        return 'error';
      }
      if (res.statusCode >= 400) {
        return 'warn';
      }
      if (res.statusCode >= 300) {
        return 'info';
      }
      return 'info';
    },

    // Custom success message
    customSuccessMessage: (req, res) => {
      return `${req.method} ${req.url} ${res.statusCode}`;
    },

    // Custom error message
    customErrorMessage: (req, res, err) => {
      return `${req.method} ${req.url} ${res.statusCode} - ${err.message}`;
    },

    // Custom attribute keys
    customAttributeKeys: {
      req: 'request',
      res: 'response',
      err: 'error',
      responseTime: 'durationMs',
    },

    // Auto-logging configuration
    autoLogging: {
      ignore: (req) => {
        // Don't log health checks
        if (req.url === '/health' || req.url === '/healthz' || req.url === '/readyz') {
          return true;
        }
        return false;
      },
    },
  });
}

/**
 * Create full logging middleware stack
 *
 * Combines:
 * 1. Request context middleware (for AsyncLocalStorage)
 * 2. Pino HTTP middleware (for automatic logging)
 */
export function createLoggingMiddleware(logger: Logger) {
  // First: context propagation
  const contextMiddleware = requestContextMiddleware(logger, {
    getUserId,
    getSessionId,
    getTenant,
  });

  // Second: pino-http for automatic logging
  const pinoMiddleware = createPinoHttpMiddleware(logger);

  // Return combined middleware
  return [contextMiddleware, pinoMiddleware];
}

/**
 * Error logging middleware
 * Should be placed after all other middleware and routes
 */
export function errorLoggingMiddleware(logger: Logger) {
  return (err: Error, req: Request, res: Response, next: any): void => {
    // Use request logger if available (has context)
    const log = (req as any).log || logger;

    log.error(
      {
        err,
        req: sanitizeRequest(req),
        statusCode: res.statusCode || 500,
      },
      'Unhandled error'
    );

    // Pass to next error handler
    next(err);
  };
}

export { requestContextMiddleware };
