/**
 * Gateway authentication + IP allowlist middleware.
 *
 * Behaviour:
 *   - Default: Auth is ENABLED (secure by default). Set `disableAuth: true` to disable.
 *   - API key is auto-generated and stored in ~/.mcp/gateway-api-key.
 *   - If `disableAuth` is true, every request passes.
 *   - If enabled, every request must have `Authorization: Bearer <apiKey>` —
 *     OR, only for browser-based clients that can't set custom headers on
 *     `new EventSource(...)`, an `?access_token=<apiKey>` query param.
 *   - If `gateway.allowedIPs` is non-empty, the client IP (as resolved
 *     by Express with `trust proxy` set) must match at least one CIDR entry.
 *   - `/health` is always exempt so external uptime monitors can probe it.
 *   - stdio transport bypasses this middleware entirely (pipe is inherently authenticated).
 *
 * Failures use generic messages to avoid leaking config.
 */

import { createRequire } from 'module';
import crypto from 'crypto';
import type { Request, Response, NextFunction } from 'express';
import logger, { sanitizeString } from '../logging/logger.js';
import { isAuthDisabled, getAllowedIPs } from '../config/auth-config.js';

const require = createRequire(import.meta.url);
// eslint-disable-next-line @typescript-eslint/no-var-requires
const ipaddr = require('ipaddr.js');

type IPv4 = ReturnType<typeof ipaddr.IPv4.prototype.constructor>;
type IPv6 = ReturnType<typeof ipaddr.IPv6.prototype.constructor>;
type IPAddress = IPv4 | IPv6;

const HEALTH_PATH = '/health';

function constantTimeEqual(a: string, b: string): boolean {
  if (typeof a !== 'string' || typeof b !== 'string') {
    return false;
  }
  const ab = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ab.length !== bb.length) {
    return false;
  }
  return crypto.timingSafeEqual(ab, bb);
}

function parseCidrs(entries: string[], name: string): Array<[IPAddress, number]> {
  const parsed: Array<[IPAddress, number]> = [];
  for (const entry of entries) {
    try {
      // ipaddr.parseCIDR throws on plain IPs — fall back to /32 (or /128 for v6).
      if (entry.includes('/')) {
        parsed.push(ipaddr.parseCIDR(entry));
      } else {
        const addr = ipaddr.parse(entry);
        const bits = addr.kind() === 'ipv6' ? 128 : 32;
        parsed.push([addr, bits]);
      }
    } catch (error) {
      const err = error as Error;
      logger.warn('Invalid CIDR entry', {
        list: sanitizeString(name),
        entry: sanitizeString(entry),
        error: err.message,
      });
    }
  }
  return parsed;
}

function ipMatches(clientIp: string, cidrs: Array<[IPAddress, number]>): boolean {
  if (cidrs.length === 0) {
    return true;
  }
  try {
    let addr = ipaddr.parse(clientIp);
    // Normalise IPv4-mapped-in-IPv6 (::ffff:127.0.0.1) to plain IPv4 so the
    // CIDR list can use familiar v4 notation.
    if (addr.kind() === 'ipv6' && (addr as IPv6).isIPv4MappedAddress()) {
      addr = (addr as IPv6).toIPv4Address();
    }
    for (const [net, bits] of cidrs) {
      if (addr.kind() !== net.kind()) {
        continue;
      }
      if (addr.match(net, bits)) {
        return true;
      }
    }
  } catch (error) {
    logger.warn('Unparseable client IP', { ip: sanitizeString(clientIp) });
  }
  return false;
}

/**
 * Build the auth middleware using the auth config file and auto-generated API key.
 * Returns an Express middleware function.
 * @param registryPath - Path to registry.json (used to locate auth config file)
 * @param autoGeneratedKey - Auto-generated API key from apikey.js
 */
export function createAuthMiddleware(
  registryPath: string | undefined,
  autoGeneratedKey = ''
): (req: Request, res: Response, next: NextFunction) => void | Response {
  // Load auth settings from auth config file (.mcp-gateway.json)
  // GATEWAY_DISABLE_AUTH env var takes precedence
  const authDisabled = isAuthDisabled(registryPath);
  const allowedIPs = getAllowedIPs(registryPath);

  const apiKey = autoGeneratedKey;
  const allowedCidrs = parseCidrs(allowedIPs, 'allowedIPs');

  if (!authDisabled && apiKey.length === 0) {
    throw new Error(
      'Auth is enabled but API key generation failed. Check logs for apikey.js errors.'
    );
  }

  if (apiKey.length > 0 && apiKey.length < 16) {
    // Fixed: Don't log API key length to avoid leaking information
    logger.warn('API key is shorter than recommended minimum (16 chars)');
  }

  const disabledViaEnv = process.env.GATEWAY_DISABLE_AUTH?.toLowerCase() === 'true';

  if (!authDisabled) {
    logger.info('Gateway auth enabled', {
      apiKeyLength: apiKey.length,
      allowedIPCount: allowedCidrs.length,
      source: disabledViaEnv ? 'GATEWAY_DISABLE_AUTH env' : 'auth config file',
    });
  } else {
    logger.warn('⚠️  SECURITY WARNING: Gateway authentication is DISABLED', {
      message: 'Anyone with network access can call APIs without authentication',
      security: 'This is INSECURE for production deployments',
      recommendation: 'Use CLI: mcp auth enable',
      source: disabledViaEnv ? 'GATEWAY_DISABLE_AUTH env' : 'auth config file',
    });
  }

  return function authMiddleware(req: Request, res: Response, next: NextFunction): void | Response {
    if (req.path === HEALTH_PATH) {
      return next();
    }
    if (authDisabled && allowedCidrs.length === 0) {
      return next();
    }

    // IP allowlist applies even when bearer auth is off — defence in depth.
    if (allowedCidrs.length > 0 && !ipMatches(req.ip ?? '', allowedCidrs)) {
      logger.warn('Rejected request: client IP not in allowlist', { ip: req.ip, path: req.path });
      return res.status(403).json({ error: 'Forbidden' });
    }

    if (authDisabled) {
      return next();
    }

    const presented = extractToken(req);
    if (presented === null || !constantTimeEqual(presented, apiKey)) {
      logger.warn('Rejected request: missing or invalid auth token', {
        ip: req.ip,
        path: req.path,
      });
      // Hint clients with the standard WWW-Authenticate header.
      res.set('WWW-Authenticate', 'Bearer realm="mcp-gateway"');
      return res.status(401).json({ error: 'Unauthorized' });
    }

    return next();
  };
}

function extractToken(req: Request): string | null {
  const header = (req.get('Authorization') ?? '').trim();
  // Fixed: Use non-backtracking regex to prevent ReDoS
  const m = header.match(/^Bearer\s+(\S+)$/i);
  if (m !== null) {
    return m[1];
  }
  // EventSource in browsers can't set headers — accept ?access_token= for /sse only.
  if (req.path === '/sse' && typeof req.query.access_token === 'string') {
    return req.query.access_token;
  }
  return null;
}

export default { createAuthMiddleware };
